name: 01 - Building Blocks

on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello, World!"
    
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Failed Step
              run: |
                echo "I will defo fail" 
                exit 1
              continue-on-error: true  # This allows the next step to run
            
            - name: Say Goodbye
              run: echo "Goodbye, World!"