name: 04-using-pre-built-actions
on:
    push:
        branches:
            - VickyLi_Local
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        # 0. Checkout code from the repository
        # 1. Install steps of our react application
        # 2. Execute automated tests
        defaults:
            run:
                working-directory: 04-Using-Pre-Built-Actions/react-app
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                    node-version: latest
            - name: Install Dependencies
              run: npm ci
            - name: Run Unit Tests
              run: npm run test 

           

            # - name: Printing Folders
            #   run: ls # List files and folders in the root directory
        

    # build:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout Repository
    #           uses: actions/checkout@v3

    #         - name: Set up Node.jsa
    #           uses: actions/setup-node@v3
    #           with:
    #               node-version: '16'

    #         - name: Install Dependencies
    #           run: npm install

    #         - name: Run Build
    #           run: npm run build

    #         - name: Upload Build Artifacts
    #           uses: actions/upload-artifact@v3
    #           with:
    #               name: build-artifacts
