name: 05-02-Event-Filters-Activity-Types
on:
  workflow_dispatch:
  pull_request:
    types:
        - closed 
    branches: #there is actually no need to add branches here since closed PRs cannot target a branch
      - main
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Run a no-op
        run: echo "Running whenever a PR is opened or synchronized AND targets the main branch."