name: 09-Using Functions
run-name: 09-Using-Functions | DATE - ${{ format('YYYY-MM-DD', github.event.head_commit.timestamp) }}
on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    echo-failure:
        runs-on: ubuntu-latest
        steps:
            - name: sleep for 10 seconds
              run: sleep 10
            - name: Demonstrate failure function
              run: |
                    echo "This step will fail intentionally."
                    exit 1
            - name: This step will be skipped due to previous failure
              if: ${{ success() }}
              run: echo "I will print if previous step succeeded."
            - name: I will execute
              if: ${{ !cancelled()}}
              run: echo "I will print if the workflow is not cancelled."
            - name: I will execute when cancelled
              if: ${{ cancelled()}}
              run: echo "I will print if the workflow is cancelled."