name: 10- Control the execution flows
run-name: 10-Execution-Flows

on:
    workflow_dispatch:
        inputs:
            pass-unit-tests:
                type: boolean
                description: 'whether unit tests passed or not'
                default: true

jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name: Lint and build
              run: |
                 # npm run lint
                 # npm run format:check
                 # npm run tsc:check
                 # npm run build
                 echo "Linting and build project completed successfully."
    unit-test:
            runs-on: ubuntu-latest
        steps:
            - name: Run Unit Tests
              run: |
                 # npm run test:unit
                 echo "Unit tests completed successfully."
            - name: Unit Tests Failing
              if: ${{ !inputs.pass-unit-tests }}
              run: |      
                  echo "Unit tests failed. Failing the job."
                  exit 1


    deploy-non-prod:
            runs-on: ubuntu-latest
            needs: 
                - lint-build
                - unit-test
            steps:
                - name: Deploy to Non-Production
                  run: |
                     echo "Deploying to non-production environment..."
                     echo "Deployment to non-production completed successfully."

    E2E-test:
            runs-on: ubuntu-latest
            needs: deploy-non-prod
            steps:
                - name: Run E2E Tests
                  run: |
                    # npm run test:e2e
                    echo "E2E tests completed successfully."
    Load-test:
            runs-on: ubuntu-latest
            needs: deploy-non-prod
            steps:
                - name: Run Load Tests
                  run: |
                        # npm run test:load
    deploy-prod:
            runs-on: ubuntu-latest
            needs: 
                - E2E-test
                - Load-test
            steps:  
                - name: Deploy to Production
                  run: |
                     echo "Deploying to production environment..."
                     echo "Deployment to production completed successfully."