name: 15-working with matrices
on:
    workflow_dispatch

jobs:
    backwards-compatability:
        name: Test on Node.js ${{ matrix.node-version }} on OS ${{ matrix.OS }}
        runs-on: ${{ matrix.OS }}
        strategy:
            matrix:
                node-version: [18.x, 22.x, 24.x]
                OS: [ubuntu-latest, windows-latest]
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                    node-version: ${{ matrix.node-version }}
            - name: Perform Tests
              run: echo "Running tests on Node.js version ${{ matrix.node-version }} on OS ${{ matrix.OS }}"