name: 16 - Working With Environment
on:
    workflow_dispatch:
        inputs:
            target-environment:
                type: environment
                default: staging
jobs:
    echo:
        runs-on: ubuntu-latest
        environment: ${{ inputs.target-environment }}
        env:
            # we can define environment variables at the job level, and they will be available to all steps within the job; also we can use expressions to set environment variables based on other variables or contexts
            # Note: vars.ENVIRONMENT is read from GitHub vars context (repo/org/environment variable), independent of this job-level env key name.
            JOB_LEVEL_ENVIRONMENT: ${{ vars.ENVIRONMENT || 'staging environment' }}
        steps:
            - name: Show target environment
              run: echo "Deploying to ${{ env.JOB_LEVEL_ENVIRONMENT }} environment"